###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"Khasim@gmail.com",
    "pin":"123456"
}


#### Get Gainers and Losers
GET http://localhost:3000/market/gainers-losers